export enum ErrorStatus {
  UNAUTHENTICATED_HTTP_RESPONSES = 'UNAUTHENTICATED_HTTP_RESPONSES',

  USER_GET_USER_ID_MANDATORY = 'USER_GET_USER_ID_MANDATORY',

  ACCOUNT_GET_LIST_MIN_KEYWORD = 'ACCOUNT_GET_LIST_MIN_KEYWORD',

  ACCOUNT_CREATE_REQ_NOT_FOUND = 'ACCOUNT_CREATE_REQ_NOT_FOUND',
  ACCOUNT_CREATE_USER_NOT_EXIST = 'ACCOUNT_CREATE_USER_NOT_EXIST',
  ACCOUNT_CREATE_USER_ID_MANDATORY = 'ACCOUNT_CREATE_USER_ID_MANDATORY',
  ACCOUNT_CREATE_TYPE_MANDATORY = 'ACCOUNT_CREATE_TYPE_MANDATORY',

  ACCOUNT_CREATE_FAILED = 'ACCOUNT_CREATE_FAILED'
}
