export enum ErrorStatus {
  UNAUTHENTICATED_HTTP_RESPONSES = 'UNAUTHENTICATED_HTTP_RESPONSES',

  TRANSACTION_CREATE_FAILED = 'TRANSACTION_CREATE_FAILED',
  TRANSACTION_CREATE_REQ_NOT_FOUND = 'TRANSACTION_CREATE_REQ_NOT_FOUND',

  TRANSACTION_GET_LIST_ACCOUNT_ID_MANDATORY = 'TRANSACTION_GET_LIST_ACCOUNT_ID_MANDATORY',
  TRANSACTION_GET_LIST_TYPE_INVALID = 'TRANSACTION_GET_LIST_TYPE_INVALID',

  TRANSACTION_CREATE_ACCOUNT_ID_MANDATORY = 'TRANSACTION_CREATE_ACCOUNT_ID_MANDATORY',
  TRANSACTION_CREATE_TYPE_INVALID = 'TRANSACTION_CREATE_TYPE_INVALID',
}
